### ISSUE TITLE
[Bug] Unwanted scrollable nature of the navigation menu 

### ISSUE THREAD

**Issue by sukumar1210** [GDSCJUET/DSC_Guna_Website#21]
**Describe the bug**
Upon opening the navigation menu the website behind is still scrollable,in normal condition it would not be a big issue but the the navigation menu's button also goes away upon scrolling. For this reason It is not possible to close the navigation menu without going back to the top if you have clicked on any of the button on the menu. If you have it takes a series of back gestures that take you back to where you initially were which simply undoes any scrolling that the internal linking of the menu components did. It makes the menu pretty much useless.

**To Reproduce**
open the website in mobile, open the navigation menu and start scrolling while noticing the same button. 

**Expected behavior**
The menu should not be scrollable or atleas the menu button should remain fixed while in navigation menu.

**Screenshots**

<img src="https://user-images.githubusercontent.com/73037127/195970646-a88b9562-b279-46d0-8828-7451c910b01d.jpg"  width="270" height="450" inline/>
<img src="https://user-images.githubusercontent.com/73037127/195970651-06899560-db8d-451c-a0f2-085ab15e664c.jpg"  width="270" height="450" />

**Smartphone (please complete the following information):**
 - Device: Samsung Tab S7 FE
- OS: Android
 - Browser: Brave
 - Version 12

**Comment by iamv1n** [comment]
Wanna Work on it? @sukumar1210

**Comment by sukumar1210** [comment]
@iamv1n sure man

**Comment by sukumar1210** [comment]
#28 PR For this issue.
