### ISSUE TITLE
[feat] Build a Contact Us Section 

### ISSUE THREAD

**Issue by iamv1n** [GDSCJUET/DSC_Guna_Website#3]
Build a Contact Us section having links of our Github, Instagram, Facebook, Email and Discord with proper Icons and Animations in the Home Page. This should not include any input form as of now the theme and color palette should be according to the Website theme.

**Comment by 1219aks** [comment]
Can I work on this?

**Comment by NNL-Keerthana** [comment]
Hi!! I am interested to work on this.

**Comment by sukumar1210** [comment]
Made the Contact us section in #31

**Comment by sukumar1210** [comment]
Made the Contact us section in #31
